### ISSUE TITLE
Flink Pipeline TODOs

### ISSUE THREAD

**Issue by peterbangert** [peterbangert/MP-DS#12]
### TODOs

- [x] Package into fat JARS
       - Vanilla Java (?)
       - @tienhngnguyen 
       - ref #13

- [ ]  Write high/low risk people to Redis [Optional]

- [x]  Implement Date logic
       - see https://github.com/peterbangert/MP-DS/pull/15

- [x]  Benchmark Test
       - Write 50k events into covid topic
       - Set kafka read index to earliest
       - See how long it takes

- [x] Increase Parallelism
       - set parallelism to 10 in flink, easy

- [ ] Asynchronous Redis I/O
       - Could very well boost performance
       - https://ci.apache.org/projects/flink/flink-docs-stable/dev/stream/operators/asyncio.html

**Comment by sumitpaulde** [comment]
Hey Jar is created we do not need vanilla Java. I will refactor the code so that we have more control over the current code. If you do not have any problem I can add the Parallelism also.
